### ISSUE TITLE
Change apikey & add config.json to .gitignore

### ISSUE THREAD

**Issue by katrinleinweber** [la-oey/Fabricator#1]
According to [ElsevierDev's advice](https://github.com/ElsevierDev/elsapy/blob/master/CONFIG.md), that file should not be included in a public git repo. Yours currently is, so please consider changing your apikey now, and then [stop tracking it in your git repo](https://duckduckgo.com/?q=git+remove+tracked+file).

**Comment by la-oey** [comment]
removed directory containing config file and added to .gitignore
